# Generated by Django 4.2.14 on 2024-07-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="symbol",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
