# Generated by Django 4.2.14 on 2024-07-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=19),
        ),
    ]
