# Generated by Django 4.2.14 on 2024-07-22 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0002_currency_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="balance",
        ),
    ]
