# Generated by Django 4.2.14 on 2024-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0003_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="flag_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
