# Generated by Django 4.2.14 on 2024-08-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0004_currency_flag_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=19, null=True
            ),
        ),
    ]
